[package]
name = "gpio_rpbled_linux_adapt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
led_gpio = { path ="../led_gpio/",features=["linux"]}